language: node_js
node_js:
- stable
branches:
  only:
  - master
  - staging
before_install:
- openssl aes-256-cbc -K $encrypted_abf29013d87f_key -iv $encrypted_abf29013d87f_iv
  -in travis_rsa.enc -out travis_rsa -d
#- chmod 600 ~/.ssh/travis_rsa
install:
- npm install -g gulp
- npm install
build: 
script: gulp travis
deploy:
- eval "$(ssh-agent -s)" # start ssh agent
- ssh-add ~/.ssh/travis_rsa
- git remote add deploy "travis@briansresume.com:/var/www/html" # deploy to html default
- git config user.name "TravisCI"
- git config user.email "travisdeploy@briansresume.com"git push -f deploy HEAD:staging # exec deploy method
notifications:
  email: false
