language: node_js
node_js:
- stable
branches:
  only:
  - master
  - staging
before_install:
- openssl aes-256-cbc -K $encrypted_cf4392f631c3_key -iv $encrypted_cf4392f631c3_iv
  -in travis_rsa.enc -out travis_rsa -d
- openssl aes-256-cbc -K $encrypted_b0b2958c016f_key -iv $encrypted_b0b2958c016f_iv
  -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
install:
- npm install -g gulp
- npm install
build: 
script: gulp travis
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    all_branches: true
notifications:
  email: false
