language: node_js
node_js:
- stable
branches:
  only:
  - master
  - staging
before_install:
- openssl aes-256-cbc -K $encrypted_abf29013d87f_key -iv $encrypted_abf29013d87f_iv
  -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host briansresume.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install -g gulp
- npm install
build: 
script: gulp travis
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    all_branches: true
notifications:
  email: false
